server {
    listen 8100;
    server_name _;
    root /var/www/html/public;
    index index.php;

    client_max_body_size 50m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_read_timeout 120;
    }

    # Blokir akses ke berkas tersembunyi kecuali .well-known.
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
